Update fly.yml

diff --git a/.github/workflows/fly.yml b/.github/workflows/fly.yml
--- a/.github/workflows/fly.yml
+++ b/.github/workflows/fly.yml
@@ -28,16 +28,15 @@ jobs:
           -user="${{ secrets.DB_BUILD_USERNAME }}"
           -password="${{ secrets.DB_BUILD_PASSWORD }}"
           info -schemas="${{ env.SCHEMAS }}"
-      - name: Flyway Info
-        run: >-
-          docker run --rm
-          --volume ${{ github.workspace }}/migrations:/flyway/sql:ro
-          "${{ env.DOCKER_IMAGE }}"
-          -licenseKey="${{ secrets.FLYWAY_LICENSE_KEY }}"
-          -url="${{ secrets.DB_BUILD_URL }}"
-          -user="${{ secrets.DB_BUILD_USERNAME }}"
-          -password="${{ secrets.DB_BUILD_PASSWORD }}" 
-          migrate -dryRunOutput="--volume ${{ github.workspace }}/dryrun.sql"
+      - name: Flyway Dry Run
+        run: |
+          # Replace the following with the appropriate Flyway command based on your setup
+          ./flyway/flyway migrate -dryRunOutput="--volume ${{ github.workspace }}/dryrun.log" -url=jdbc:singlestore://svc-4f5248c3-aa85-45d7-a05f-eebd9cc0ccf9-dml.aws-virginia-6.svc.singlestore.com:3306/devdb -user=admin -password=Ovin@123
+          if [ $? -ne 0 ]; then
+            echo "Flyway dry run failed. Check the dry run log:"
+            cat /tmp/flyway_dryrun.log
+            exit 1
+          fi
           
   Deploy-Test:
       name: Deploy Test
